### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by lu-zero** [sifis-home/sifis-hazards#1]
- [ ] move and simplify the jsonld -> rust generator here
- [ ] store the generated header at release tags
- [ ] make sure that the structures are documented
- [ ] make sure that the structures support serde
- [ ] make sure that the structures implement Display and Debug
